name: flutter_poki_sdk
description: The Poki SDK for Flutter (based on sdk.poki.com/html5.html)
version: 1.0.0
repository: https://github.com/imaNNeo/flutter_poki_sdk
publish_to: none

environment:
  sdk: ^3.6.0

dependencies:
  js_interop: ^0.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
